### ISSUE TITLE
Add Zenodo DOI

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaPlots.jl#26]
### What and Why

1. Go to https://zenodo.org/ and log in with your GitHub account
2. Link the repository to Zenodo to generate the DOI
3. Copy the DOI number and update the README file with the URL to the Zenodo DOI in the badge

**Comment by gnawin** [comment]
According to Zenodo -> My account -> Github (see below), a release is needed before a DOI is created.
![image](https://github.com/TulipaEnergy/TulipaPlots.jl/assets/125902905/645b9fd8-28af-4918-b042-ec4b0be115b0)

Shall we create a release? Until then, blocked by #3.

**Comment by clizbe** [comment]
Go for it! :)

**Comment by gnawin** [comment]
Waiting for the release (which will come after 3 days).
